openapi: 3.0.2
info:
  title: timerProcess
  description: A service to get the time to access the platform architecture information
  license:
    name: Apache 2.0
  version: 0.0.1

servers:
  - url: http://localhost:8080/openAPI/

paths:
  /timer:
    get:
      summary: Returns time information on a trivial function to do a basic test connection speed to server
      operationId: timer.check_connection_type
      responses:
        '200':
          description: timed basic response time for server architecture
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/timer"

components:
  schemas:
    timer:
      type: "object"
      required:
        - "connection"
      properties:
        connection:
          type: string

